create table search_applicant_data (
	applicant_id INT,
	firstname VARCHAR(50),
	lastname VARCHAR(50),
	Gender VARCHAR(50),
	email_added VARCHAR(50),
	phone_number VARCHAR(50),
	yearsofexperience INT,
	specialization VARCHAR(18),
	favoritedbms VARCHAR(10),
	favoritefrontendframework VARCHAR(7)
);
insert into search_applicant_data (applicant_id, firstname, lastname, Gender, email_added, phone_number, yearsofexperience, specialization, favoritedbms, favoritefrontendframework) values (64, 'Miguelita', 'Alanbrooke', 'Female', 'malanbrooke0@mtv.com', '603-857-8745', 23, 'Data Science', 'PostgreSQL', 'Angular');
insert into search_applicant_data (applicant_id, firstname, lastname, Gender, email_added, phone_number, yearsofexperience, specialization, favoritedbms, favoritefrontendframework) values (99, 'Alair', 'Eagling', 'Male', 'aeagling1@hc360.com', '524-677-1115', 19, 'Frontend Developer', 'PostgreSQL', 'Vue.js');
insert into search_applicant_data (applicant_id, firstname, lastname, Gender, email_added, phone_number, yearsofexperience, specialization, favoritedbms, favoritefrontendframework) values (15, 'Trina', 'Yousef', 'Female', 'tyousef2@oaic.gov.au', '358-926-7727', 22, 'Data Science', 'PostgreSQL', 'React');
insert into search_applicant_data (applicant_id, firstname, lastname, Gender, email_added, phone_number, yearsofexperience, specialization, favoritedbms, favoritefrontendframework) values (73, 'Nora', 'Stodit', 'Female', 'nstodit3@dropbox.com', '335-647-5362', 3, 'Web Designer', 'MongoDB', 'React');
insert into search_applicant_data (applicant_id, firstname, lastname, Gender, email_added, phone_number, yearsofexperience, specialization, favoritedbms, favoritefrontendframework) values (78, 'Riane', 'Glen', 'Female', 'rglen4@yellowpages.com', '531-865-3143', 8, 'Backend Developer', 'MySQL', 'React');
insert into search_applicant_data (applicant_id, firstname, lastname, Gender, email_added, phone_number, yearsofexperience, specialization, favoritedbms, favoritefrontendframework) values (49, 'Charmaine', 'Garwood', 'Female', 'cgarwood5@noaa.gov', '805-987-5096', 8, 'Data Science', 'PostgreSQL', 'React');
insert into search_applicant_data (applicant_id, firstname, lastname, Gender, email_added, phone_number, yearsofexperience, specialization, favoritedbms, favoritefrontendframework) values (71, 'Steward', 'Pickwell', 'Male', 'spickwell6@drupal.org', '506-840-6485', 22, 'Frontend Developer', 'MySQL', 'Vue.js');
insert into search_applicant_data (applicant_id, firstname, lastname, Gender, email_added, phone_number, yearsofexperience, specialization, favoritedbms, favoritefrontendframework) values (97, 'Lenette', 'Sturgis', 'Female', 'lsturgis7@gizmodo.com', '445-537-2865', 20, 'Web Development', 'MySQL', 'Angular');
insert into search_applicant_data (applicant_id, firstname, lastname, Gender, email_added, phone_number, yearsofexperience, specialization, favoritedbms, favoritefrontendframework) values (73, 'Garner', 'Levine', 'Male', 'glevine8@zimbio.com', '788-872-4787', 0, 'Web Development', 'MySQL', 'React');
insert into search_applicant_data (applicant_id, firstname, lastname, Gender, email_added, phone_number, yearsofexperience, specialization, favoritedbms, favoritefrontendframework) values (3, 'Jennilee', 'Spollen', 'Female', 'jspollen9@over-blog.com', '883-268-8216', 14, 'Web Designer', 'MySQL', 'Angular');
insert into search_applicant_data (applicant_id, firstname, lastname, Gender, email_added, phone_number, yearsofexperience, specialization, favoritedbms, favoritefrontendframework) values (12, 'Ramon', 'Vassel', 'Male', 'rvassela@squarespace.com', '521-101-8166', 5, 'Web Development', 'PostgreSQL', 'Angular');
insert into search_applicant_data (applicant_id, firstname, lastname, Gender, email_added, phone_number, yearsofexperience, specialization, favoritedbms, favoritefrontendframework) values (43, 'Tulley', 'Aristide', 'Male', 'taristideb@blogs.com', '672-651-3148', 3, 'Web Development', 'MongoDB', 'Angular');
insert into search_applicant_data (applicant_id, firstname, lastname, Gender, email_added, phone_number, yearsofexperience, specialization, favoritedbms, favoritefrontendframework) values (13, 'Meade', 'Meriott', 'Male', 'mmeriottc@feedburner.com', '262-999-9982', 17, 'DevOps', 'PostgreSQL', 'Angular');
insert into search_applicant_data (applicant_id, firstname, lastname, Gender, email_added, phone_number, yearsofexperience, specialization, favoritedbms, favoritefrontendframework) values (85, 'Catherin', 'Linner', 'Female', 'clinnerd@shinystat.com', '556-428-7507', 10, 'Frontend Developer', 'MySQL', 'Vue.js');
insert into search_applicant_data (applicant_id, firstname, lastname, Gender, email_added, phone_number, yearsofexperience, specialization, favoritedbms, favoritefrontendframework) values (82, 'Lyle', 'Pedreschi', 'Bigender', 'lpedreschie@ucsd.edu', '131-953-1753', 28, 'Web Development', 'MongoDB', 'React');
insert into search_applicant_data (applicant_id, firstname, lastname, Gender, email_added, phone_number, yearsofexperience, specialization, favoritedbms, favoritefrontendframework) values (86, 'Reidar', 'Dalwood', 'Male', 'rdalwoodf@psu.edu', '451-404-7842', 21, 'Web Designer', 'MySQL', 'Vue.js');
insert into search_applicant_data (applicant_id, firstname, lastname, Gender, email_added, phone_number, yearsofexperience, specialization, favoritedbms, favoritefrontendframework) values (50, 'Tommie', 'Whitwell', 'Bigender', 'twhitwellg@comsenz.com', '132-227-0287', 11, 'Data Science', 'MySQL', 'Vue.js');
insert into search_applicant_data (applicant_id, firstname, lastname, Gender, email_added, phone_number, yearsofexperience, specialization, favoritedbms, favoritefrontendframework) values (21, 'Lynde', 'Juett', 'Female', 'ljuetth@google.com.au', '181-127-6358', 13, 'Frontend Developer', 'PostgreSQL', 'React');
insert into search_applicant_data (applicant_id, firstname, lastname, Gender, email_added, phone_number, yearsofexperience, specialization, favoritedbms, favoritefrontendframework) values (59, 'Frank', 'Dorward', 'Male', 'fdorwardi@unc.edu', '298-267-0638', 14, 'Backend Developer', 'MongoDB', 'Vue.js');
insert into search_applicant_data (applicant_id, firstname, lastname, Gender, email_added, phone_number, yearsofexperience, specialization, favoritedbms, favoritefrontendframework) values (62, 'Emmerich', 'Peters', 'Male', 'epetersj@issuu.com', '581-131-8686', 4, 'Web Designer', 'PostgreSQL', 'React');
insert into search_applicant_data (applicant_id, firstname, lastname, Gender, email_added, phone_number, yearsofexperience, specialization, favoritedbms, favoritefrontendframework) values (55, 'Mackenzie', 'Ulyatt', 'Male', 'mulyattk@mapy.cz', '865-311-1783', 28, 'DevOps', 'MongoDB', 'React');
insert into search_applicant_data (applicant_id, firstname, lastname, Gender, email_added, phone_number, yearsofexperience, specialization, favoritedbms, favoritefrontendframework) values (4, 'Heindrick', 'Lamburne', 'Male', 'hlamburnel@loc.gov', '859-739-2033', 13, 'Backend Developer', 'PostgreSQL', 'React');
insert into search_applicant_data (applicant_id, firstname, lastname, Gender, email_added, phone_number, yearsofexperience, specialization, favoritedbms, favoritefrontendframework) values (65, 'Gifford', 'Jorn', 'Male', 'gjornm@shutterfly.com', '779-690-5141', 24, 'DevOps', 'MongoDB', 'Angular');
insert into search_applicant_data (applicant_id, firstname, lastname, Gender, email_added, phone_number, yearsofexperience, specialization, favoritedbms, favoritefrontendframework) values (75, 'Beitris', 'Barkes', 'Female', 'bbarkesn@fda.gov', '318-782-3624', 19, 'Data Science', 'PostgreSQL', 'Vue.js');
insert into search_applicant_data (applicant_id, firstname, lastname, Gender, email_added, phone_number, yearsofexperience, specialization, favoritedbms, favoritefrontendframework) values (61, 'Meagan', 'Drezzer', 'Female', 'mdrezzero@meetup.com', '726-761-5366', 11, 'DevOps', 'MongoDB', 'React');
insert into search_applicant_data (applicant_id, firstname, lastname, Gender, email_added, phone_number, yearsofexperience, specialization, favoritedbms, favoritefrontendframework) values (15, 'Meta', 'Keam', 'Female', 'mkeamp@imageshack.us', '369-158-8061', 4, 'Web Designer', 'MySQL', 'React');
insert into search_applicant_data (applicant_id, firstname, lastname, Gender, email_added, phone_number, yearsofexperience, specialization, favoritedbms, favoritefrontendframework) values (58, 'Laure', 'Wycliff', 'Female', 'lwycliffq@sogou.com', '539-475-0035', 14, 'Web Development', 'MySQL', 'Angular');
insert into search_applicant_data (applicant_id, firstname, lastname, Gender, email_added, phone_number, yearsofexperience, specialization, favoritedbms, favoritefrontendframework) values (93, 'Wang', 'Nozzolinii', 'Male', 'wnozzoliniir@ameblo.jp', '635-255-0633', 18, 'DevOps', 'PostgreSQL', 'React');
insert into search_applicant_data (applicant_id, firstname, lastname, Gender, email_added, phone_number, yearsofexperience, specialization, favoritedbms, favoritefrontendframework) values (38, 'Brietta', 'Gallichan', 'Female', 'bgallichans@digg.com', '676-300-7001', 16, 'Frontend Developer', 'PostgreSQL', 'React');
insert into search_applicant_data (applicant_id, firstname, lastname, Gender, email_added, phone_number, yearsofexperience, specialization, favoritedbms, favoritefrontendframework) values (30, 'Maury', 'Birtwhistle', 'Male', 'mbirtwhistlet@cbslocal.com', '552-691-1304', 1, 'Web Development', 'MySQL', 'React');
insert into search_applicant_data (applicant_id, firstname, lastname, Gender, email_added, phone_number, yearsofexperience, specialization, favoritedbms, favoritefrontendframework) values (51, 'Gerti', 'Whitmore', 'Female', 'gwhitmoreu@cdc.gov', '118-453-8232', 0, 'Data Science', 'PostgreSQL', 'React');
insert into search_applicant_data (applicant_id, firstname, lastname, Gender, email_added, phone_number, yearsofexperience, specialization, favoritedbms, favoritefrontendframework) values (37, 'Lonnard', 'Tomaszczyk', 'Male', 'ltomaszczykv@cnbc.com', '474-951-8698', 11, 'Data Science', 'MySQL', 'React');
insert into search_applicant_data (applicant_id, firstname, lastname, Gender, email_added, phone_number, yearsofexperience, specialization, favoritedbms, favoritefrontendframework) values (5, 'Felisha', 'Batcheldor', 'Genderqueer', 'fbatcheldorw@earthlink.net', '842-388-4079', 17, 'Frontend Developer', 'PostgreSQL', 'Angular');
insert into search_applicant_data (applicant_id, firstname, lastname, Gender, email_added, phone_number, yearsofexperience, specialization, favoritedbms, favoritefrontendframework) values (74, 'Nathanil', 'Colman', 'Male', 'ncolmanx@flavors.me', '987-298-4445', 26, 'Web Designer', 'MongoDB', 'Vue.js');
insert into search_applicant_data (applicant_id, firstname, lastname, Gender, email_added, phone_number, yearsofexperience, specialization, favoritedbms, favoritefrontendframework) values (25, 'Duncan', 'Preist', 'Male', 'dpreisty@paginegialle.it', '294-309-9338', 6, 'Web Development', 'MongoDB', 'Vue.js');
insert into search_applicant_data (applicant_id, firstname, lastname, Gender, email_added, phone_number, yearsofexperience, specialization, favoritedbms, favoritefrontendframework) values (30, 'Lissa', 'Baumber', 'Female', 'lbaumberz@youtube.com', '218-772-6484', 16, 'DevOps', 'MySQL', 'React');
insert into search_applicant_data (applicant_id, firstname, lastname, Gender, email_added, phone_number, yearsofexperience, specialization, favoritedbms, favoritefrontendframework) values (67, 'Bucky', 'Aleksandrikin', 'Male', 'baleksandrikin10@wp.com', '274-640-0568', 24, 'Backend Developer', 'MongoDB', 'Angular');
insert into search_applicant_data (applicant_id, firstname, lastname, Gender, email_added, phone_number, yearsofexperience, specialization, favoritedbms, favoritefrontendframework) values (81, 'Federico', 'Mewhirter', 'Male', 'fmewhirter11@angelfire.com', '106-844-1880', 12, 'Data Science', 'MySQL', 'Vue.js');
insert into search_applicant_data (applicant_id, firstname, lastname, Gender, email_added, phone_number, yearsofexperience, specialization, favoritedbms, favoritefrontendframework) values (87, 'Maury', 'Knotte', 'Male', 'mknotte12@posterous.com', '307-972-3013', 20, 'Frontend Developer', 'PostgreSQL', 'Vue.js');
insert into search_applicant_data (applicant_id, firstname, lastname, Gender, email_added, phone_number, yearsofexperience, specialization, favoritedbms, favoritefrontendframework) values (41, 'Gisele', 'Nowill', 'Polygender', 'gnowill13@tmall.com', '819-210-5731', 19, 'DevOps', 'MongoDB', 'Vue.js');
insert into search_applicant_data (applicant_id, firstname, lastname, Gender, email_added, phone_number, yearsofexperience, specialization, favoritedbms, favoritefrontendframework) values (38, 'Quinn', 'Verling', 'Male', 'qverling14@prlog.org', '223-821-0368', 20, 'Data Science', 'PostgreSQL', 'Angular');
insert into search_applicant_data (applicant_id, firstname, lastname, Gender, email_added, phone_number, yearsofexperience, specialization, favoritedbms, favoritefrontendframework) values (88, 'Clerissa', 'Kincey', 'Female', 'ckincey15@rediff.com', '753-180-8968', 13, 'Web Development', 'MongoDB', 'React');
insert into search_applicant_data (applicant_id, firstname, lastname, Gender, email_added, phone_number, yearsofexperience, specialization, favoritedbms, favoritefrontendframework) values (58, 'Emmalee', 'Pesik', 'Female', 'epesik16@qq.com', '390-470-4628', 27, 'Backend Developer', 'MySQL', 'Angular');
insert into search_applicant_data (applicant_id, firstname, lastname, Gender, email_added, phone_number, yearsofexperience, specialization, favoritedbms, favoritefrontendframework) values (39, 'Abagael', 'Kohnen', 'Female', 'akohnen17@goo.ne.jp', '556-165-6758', 11, 'Backend Developer', 'MySQL', 'React');
insert into search_applicant_data (applicant_id, firstname, lastname, Gender, email_added, phone_number, yearsofexperience, specialization, favoritedbms, favoritefrontendframework) values (33, 'Federico', 'Bowkett', 'Male', 'fbowkett18@soundcloud.com', '349-575-2294', 15, 'Web Development', 'MySQL', 'Vue.js');
insert into search_applicant_data (applicant_id, firstname, lastname, Gender, email_added, phone_number, yearsofexperience, specialization, favoritedbms, favoritefrontendframework) values (70, 'Cory', 'Stapells', 'Female', 'cstapells19@dagondesign.com', '350-990-2536', 14, 'Web Development', 'MySQL', 'Vue.js');
insert into search_applicant_data (applicant_id, firstname, lastname, Gender, email_added, phone_number, yearsofexperience, specialization, favoritedbms, favoritefrontendframework) values (99, 'Gare', 'Bercevelo', 'Male', 'gbercevelo1a@skype.com', '388-929-1777', 2, 'Frontend Developer', 'MongoDB', 'Angular');
insert into search_applicant_data (applicant_id, firstname, lastname, Gender, email_added, phone_number, yearsofexperience, specialization, favoritedbms, favoritefrontendframework) values (91, 'Elladine', 'Warry', 'Female', 'ewarry1b@imgur.com', '457-585-0662', 19, 'Data Science', 'MySQL', 'Angular');
insert into search_applicant_data (applicant_id, firstname, lastname, Gender, email_added, phone_number, yearsofexperience, specialization, favoritedbms, favoritefrontendframework) values (58, 'Emelda', 'Kleinplatz', 'Female', 'ekleinplatz1c@seesaa.net', '888-994-8035', 3, 'Web Development', 'PostgreSQL', 'Vue.js');
insert into search_applicant_data (applicant_id, firstname, lastname, Gender, email_added, phone_number, yearsofexperience, specialization, favoritedbms, favoritefrontendframework) values (92, 'Christyna', 'Clapham', 'Non-binary', 'cclapham1d@jiathis.com', '498-704-9311', 27, 'Web Designer', 'PostgreSQL', 'Vue.js');
insert into search_applicant_data (applicant_id, firstname, lastname, Gender, email_added, phone_number, yearsofexperience, specialization, favoritedbms, favoritefrontendframework) values (46, 'Nicholas', 'Livett', 'Genderqueer', 'nlivett1e@issuu.com', '585-255-9713', 18, 'DevOps', 'MySQL', 'React');
insert into search_applicant_data (applicant_id, firstname, lastname, Gender, email_added, phone_number, yearsofexperience, specialization, favoritedbms, favoritefrontendframework) values (67, 'Rudy', 'Cristofor', 'Agender', 'rcristofor1f@wikipedia.org', '216-332-1033', 28, 'DevOps', 'PostgreSQL', 'Vue.js');
insert into search_applicant_data (applicant_id, firstname, lastname, Gender, email_added, phone_number, yearsofexperience, specialization, favoritedbms, favoritefrontendframework) values (94, 'Jaye', 'Alvares', 'Male', 'jalvares1g@blogs.com', '219-440-5834', 8, 'DevOps', 'MySQL', 'Vue.js');
insert into search_applicant_data (applicant_id, firstname, lastname, Gender, email_added, phone_number, yearsofexperience, specialization, favoritedbms, favoritefrontendframework) values (91, 'Hersh', 'Forlonge', 'Male', 'hforlonge1h@studiopress.com', '989-566-7349', 6, 'Frontend Developer', 'MySQL', 'Vue.js');
insert into search_applicant_data (applicant_id, firstname, lastname, Gender, email_added, phone_number, yearsofexperience, specialization, favoritedbms, favoritefrontendframework) values (52, 'Olivia', 'Ellacombe', 'Female', 'oellacombe1i@netlog.com', '256-197-4810', 3, 'Backend Developer', 'MongoDB', 'React');
insert into search_applicant_data (applicant_id, firstname, lastname, Gender, email_added, phone_number, yearsofexperience, specialization, favoritedbms, favoritefrontendframework) values (34, 'Selina', 'Malamore', 'Female', 'smalamore1j@msn.com', '632-527-4992', 17, 'Backend Developer', 'PostgreSQL', 'React');
insert into search_applicant_data (applicant_id, firstname, lastname, Gender, email_added, phone_number, yearsofexperience, specialization, favoritedbms, favoritefrontendframework) values (6, 'Sharlene', 'Handrahan', 'Female', 'shandrahan1k@dropbox.com', '763-689-6996', 3, 'Web Development', 'MySQL', 'React');
insert into search_applicant_data (applicant_id, firstname, lastname, Gender, email_added, phone_number, yearsofexperience, specialization, favoritedbms, favoritefrontendframework) values (29, 'Iona', 'Leverage', 'Genderfluid', 'ileverage1l@themeforest.net', '574-844-1381', 23, 'Data Science', 'MySQL', 'React');
insert into search_applicant_data (applicant_id, firstname, lastname, Gender, email_added, phone_number, yearsofexperience, specialization, favoritedbms, favoritefrontendframework) values (11, 'Maressa', 'Orwin', 'Female', 'morwin1m@over-blog.com', '742-939-3608', 0, 'Data Science', 'MySQL', 'Vue.js');
insert into search_applicant_data (applicant_id, firstname, lastname, Gender, email_added, phone_number, yearsofexperience, specialization, favoritedbms, favoritefrontendframework) values (70, 'Cristy', 'Hillen', 'Female', 'chillen1n@plala.or.jp', '812-133-6698', 21, 'Data Science', 'MySQL', 'Angular');
insert into search_applicant_data (applicant_id, firstname, lastname, Gender, email_added, phone_number, yearsofexperience, specialization, favoritedbms, favoritefrontendframework) values (60, 'Allin', 'Isham', 'Male', 'aisham1o@elegantthemes.com', '939-482-1309', 24, 'Web Designer', 'MySQL', 'Angular');
insert into search_applicant_data (applicant_id, firstname, lastname, Gender, email_added, phone_number, yearsofexperience, specialization, favoritedbms, favoritefrontendframework) values (15, 'Julia', 'Karpf', 'Female', 'jkarpf1p@slate.com', '496-174-1400', 14, 'DevOps', 'PostgreSQL', 'Vue.js');
insert into search_applicant_data (applicant_id, firstname, lastname, Gender, email_added, phone_number, yearsofexperience, specialization, favoritedbms, favoritefrontendframework) values (85, 'Enrichetta', 'Nealy', 'Female', 'enealy1q@booking.com', '958-690-8896', 28, 'DevOps', 'MySQL', 'Vue.js');
insert into search_applicant_data (applicant_id, firstname, lastname, Gender, email_added, phone_number, yearsofexperience, specialization, favoritedbms, favoritefrontendframework) values (64, 'Zolly', 'Orbell', 'Male', 'zorbell1r@gmpg.org', '926-638-2116', 27, 'Web Development', 'PostgreSQL', 'Vue.js');
insert into search_applicant_data (applicant_id, firstname, lastname, Gender, email_added, phone_number, yearsofexperience, specialization, favoritedbms, favoritefrontendframework) values (64, 'Scot', 'Burdass', 'Non-binary', 'sburdass1s@squarespace.com', '578-970-6593', 5, 'Web Designer', 'PostgreSQL', 'React');
insert into search_applicant_data (applicant_id, firstname, lastname, Gender, email_added, phone_number, yearsofexperience, specialization, favoritedbms, favoritefrontendframework) values (80, 'Marillin', 'Hansley', 'Female', 'mhansley1t@seesaa.net', '235-418-8059', 8, 'Data Science', 'MongoDB', 'Angular');
insert into search_applicant_data (applicant_id, firstname, lastname, Gender, email_added, phone_number, yearsofexperience, specialization, favoritedbms, favoritefrontendframework) values (53, 'Valentine', 'Boyack', 'Male', 'vboyack1u@soup.io', '988-660-2677', 9, 'Backend Developer', 'PostgreSQL', 'Vue.js');
insert into search_applicant_data (applicant_id, firstname, lastname, Gender, email_added, phone_number, yearsofexperience, specialization, favoritedbms, favoritefrontendframework) values (15, 'Leonidas', 'Evans', 'Male', 'levans1v@time.com', '834-455-0768', 15, 'Web Development', 'PostgreSQL', 'Vue.js');
insert into search_applicant_data (applicant_id, firstname, lastname, Gender, email_added, phone_number, yearsofexperience, specialization, favoritedbms, favoritefrontendframework) values (8, 'Madelyn', 'Seefus', 'Female', 'mseefus1w@gizmodo.com', '377-153-2191', 23, 'Frontend Developer', 'MySQL', 'Vue.js');
insert into search_applicant_data (applicant_id, firstname, lastname, Gender, email_added, phone_number, yearsofexperience, specialization, favoritedbms, favoritefrontendframework) values (78, 'Reinaldos', 'Zorzini', 'Male', 'rzorzini1x@ibm.com', '620-995-7406', 5, 'Backend Developer', 'PostgreSQL', 'Angular');
insert into search_applicant_data (applicant_id, firstname, lastname, Gender, email_added, phone_number, yearsofexperience, specialization, favoritedbms, favoritefrontendframework) values (70, 'Neila', 'Bentote', 'Female', 'nbentote1y@hatena.ne.jp', '695-645-0266', 26, 'Data Science', 'PostgreSQL', 'React');
insert into search_applicant_data (applicant_id, firstname, lastname, Gender, email_added, phone_number, yearsofexperience, specialization, favoritedbms, favoritefrontendframework) values (67, 'Pamela', 'Petrina', 'Female', 'ppetrina1z@prweb.com', '720-476-0701', 29, 'Backend Developer', 'MongoDB', 'Vue.js');
insert into search_applicant_data (applicant_id, firstname, lastname, Gender, email_added, phone_number, yearsofexperience, specialization, favoritedbms, favoritefrontendframework) values (41, 'Vernice', 'Scintsbury', 'Female', 'vscintsbury20@google.ru', '596-726-1864', 22, 'DevOps', 'MongoDB', 'Angular');
insert into search_applicant_data (applicant_id, firstname, lastname, Gender, email_added, phone_number, yearsofexperience, specialization, favoritedbms, favoritefrontendframework) values (9, 'Bank', 'Wessing', 'Male', 'bwessing21@accuweather.com', '555-786-7872', 2, 'Backend Developer', 'MySQL', 'React');
insert into search_applicant_data (applicant_id, firstname, lastname, Gender, email_added, phone_number, yearsofexperience, specialization, favoritedbms, favoritefrontendframework) values (39, 'Jasper', 'Rudiger', 'Genderqueer', 'jrudiger22@google.com', '748-225-0692', 27, 'Web Development', 'MySQL', 'Vue.js');
insert into search_applicant_data (applicant_id, firstname, lastname, Gender, email_added, phone_number, yearsofexperience, specialization, favoritedbms, favoritefrontendframework) values (20, 'Karney', 'Matisoff', 'Male', 'kmatisoff23@shinystat.com', '351-880-7540', 8, 'DevOps', 'PostgreSQL', 'React');
insert into search_applicant_data (applicant_id, firstname, lastname, Gender, email_added, phone_number, yearsofexperience, specialization, favoritedbms, favoritefrontendframework) values (4, 'Giffy', 'Barnewall', 'Male', 'gbarnewall24@aboutads.info', '522-796-9673', 24, 'Web Development', 'MySQL', 'React');
insert into search_applicant_data (applicant_id, firstname, lastname, Gender, email_added, phone_number, yearsofexperience, specialization, favoritedbms, favoritefrontendframework) values (84, 'Graham', 'Rodinger', 'Male', 'grodinger25@phpbb.com', '527-226-2993', 22, 'Web Development', 'MySQL', 'React');
insert into search_applicant_data (applicant_id, firstname, lastname, Gender, email_added, phone_number, yearsofexperience, specialization, favoritedbms, favoritefrontendframework) values (83, 'Ted', 'Slipper', 'Male', 'tslipper26@360.cn', '253-180-8700', 12, 'Frontend Developer', 'MySQL', 'Vue.js');
insert into search_applicant_data (applicant_id, firstname, lastname, Gender, email_added, phone_number, yearsofexperience, specialization, favoritedbms, favoritefrontendframework) values (68, 'Wiley', 'Klimke', 'Male', 'wklimke27@washington.edu', '973-303-7487', 6, 'Backend Developer', 'MySQL', 'Vue.js');
insert into search_applicant_data (applicant_id, firstname, lastname, Gender, email_added, phone_number, yearsofexperience, specialization, favoritedbms, favoritefrontendframework) values (48, 'Jayme', 'Du Fray', 'Female', 'jdufray28@gizmodo.com', '701-514-8071', 24, 'Data Science', 'PostgreSQL', 'Angular');
insert into search_applicant_data (applicant_id, firstname, lastname, Gender, email_added, phone_number, yearsofexperience, specialization, favoritedbms, favoritefrontendframework) values (73, 'Biddy', 'Croall', 'Female', 'bcroall29@360.cn', '659-239-3725', 13, 'Web Designer', 'MongoDB', 'Vue.js');
insert into search_applicant_data (applicant_id, firstname, lastname, Gender, email_added, phone_number, yearsofexperience, specialization, favoritedbms, favoritefrontendframework) values (67, 'Hubey', 'Curedell', 'Male', 'hcuredell2a@ca.gov', '145-368-2291', 14, 'DevOps', 'MongoDB', 'Angular');
insert into search_applicant_data (applicant_id, firstname, lastname, Gender, email_added, phone_number, yearsofexperience, specialization, favoritedbms, favoritefrontendframework) values (65, 'Filbert', 'Hallibone', 'Male', 'fhallibone2b@epa.gov', '613-623-5022', 26, 'DevOps', 'MySQL', 'React');
insert into search_applicant_data (applicant_id, firstname, lastname, Gender, email_added, phone_number, yearsofexperience, specialization, favoritedbms, favoritefrontendframework) values (92, 'Sig', 'Micklewright', 'Male', 'smicklewright2c@dagondesign.com', '142-291-3477', 14, 'Frontend Developer', 'MongoDB', 'React');
insert into search_applicant_data (applicant_id, firstname, lastname, Gender, email_added, phone_number, yearsofexperience, specialization, favoritedbms, favoritefrontendframework) values (50, 'Dotty', 'Hattam', 'Female', 'dhattam2d@privacy.gov.au', '470-200-2958', 15, 'Frontend Developer', 'MongoDB', 'Angular');
insert into search_applicant_data (applicant_id, firstname, lastname, Gender, email_added, phone_number, yearsofexperience, specialization, favoritedbms, favoritefrontendframework) values (23, 'Field', 'Hornig', 'Male', 'fhornig2e@europa.eu', '418-452-9073', 24, 'Web Development', 'MongoDB', 'Vue.js');
insert into search_applicant_data (applicant_id, firstname, lastname, Gender, email_added, phone_number, yearsofexperience, specialization, favoritedbms, favoritefrontendframework) values (47, 'Dacie', 'Tomlins', 'Female', 'dtomlins2f@moonfruit.com', '170-132-5502', 11, 'Frontend Developer', 'PostgreSQL', 'React');
insert into search_applicant_data (applicant_id, firstname, lastname, Gender, email_added, phone_number, yearsofexperience, specialization, favoritedbms, favoritefrontendframework) values (81, 'Elisha', 'Bourhill', 'Female', 'ebourhill2g@friendfeed.com', '261-532-7403', 19, 'DevOps', 'MySQL', 'Angular');
insert into search_applicant_data (applicant_id, firstname, lastname, Gender, email_added, phone_number, yearsofexperience, specialization, favoritedbms, favoritefrontendframework) values (85, 'Laurent', 'Keyho', 'Male', 'lkeyho2h@godaddy.com', '676-627-0433', 2, 'Backend Developer', 'PostgreSQL', 'React');
insert into search_applicant_data (applicant_id, firstname, lastname, Gender, email_added, phone_number, yearsofexperience, specialization, favoritedbms, favoritefrontendframework) values (89, 'Malva', 'Erangy', 'Female', 'merangy2i@businessinsider.com', '319-490-3980', 14, 'Web Development', 'MongoDB', 'Angular');
insert into search_applicant_data (applicant_id, firstname, lastname, Gender, email_added, phone_number, yearsofexperience, specialization, favoritedbms, favoritefrontendframework) values (71, 'Lelah', 'Swynfen', 'Female', 'lswynfen2j@storify.com', '193-198-5107', 6, 'Web Development', 'PostgreSQL', 'Vue.js');
insert into search_applicant_data (applicant_id, firstname, lastname, Gender, email_added, phone_number, yearsofexperience, specialization, favoritedbms, favoritefrontendframework) values (33, 'Shadow', 'Blader', 'Male', 'sblader2k@statcounter.com', '366-634-5896', 3, 'Data Science', 'MongoDB', 'Vue.js');
insert into search_applicant_data (applicant_id, firstname, lastname, Gender, email_added, phone_number, yearsofexperience, specialization, favoritedbms, favoritefrontendframework) values (98, 'Sanson', 'Lackeye', 'Male', 'slackeye2l@nationalgeographic.com', '805-121-1776', 16, 'Data Science', 'PostgreSQL', 'Angular');
insert into search_applicant_data (applicant_id, firstname, lastname, Gender, email_added, phone_number, yearsofexperience, specialization, favoritedbms, favoritefrontendframework) values (76, 'Aldwin', 'Bauld', 'Male', 'abauld2m@cargocollective.com', '949-873-9824', 5, 'DevOps', 'PostgreSQL', 'React');
insert into search_applicant_data (applicant_id, firstname, lastname, Gender, email_added, phone_number, yearsofexperience, specialization, favoritedbms, favoritefrontendframework) values (3, 'Mischa', 'Tulleth', 'Genderfluid', 'mtulleth2n@pinterest.com', '647-914-7298', 22, 'Backend Developer', 'MongoDB', 'Vue.js');
insert into search_applicant_data (applicant_id, firstname, lastname, Gender, email_added, phone_number, yearsofexperience, specialization, favoritedbms, favoritefrontendframework) values (94, 'Antons', 'Punter', 'Genderqueer', 'apunter2o@narod.ru', '486-775-0998', 18, 'Web Development', 'MongoDB', 'React');
insert into search_applicant_data (applicant_id, firstname, lastname, Gender, email_added, phone_number, yearsofexperience, specialization, favoritedbms, favoritefrontendframework) values (28, 'Trace', 'Hebbs', 'Male', 'thebbs2p@auda.org.au', '342-553-4305', 10, 'Data Science', 'MongoDB', 'Vue.js');
insert into search_applicant_data (applicant_id, firstname, lastname, Gender, email_added, phone_number, yearsofexperience, specialization, favoritedbms, favoritefrontendframework) values (12, 'Dorine', 'Kittredge', 'Female', 'dkittredge2q@examiner.com', '996-639-5978', 15, 'Web Development', 'MySQL', 'Angular');
insert into search_applicant_data (applicant_id, firstname, lastname, Gender, email_added, phone_number, yearsofexperience, specialization, favoritedbms, favoritefrontendframework) values (61, 'Pail', 'Marryatt', 'Genderqueer', 'pmarryatt2r@nih.gov', '943-252-6575', 4, 'Backend Developer', 'MongoDB', 'Vue.js');
